### ISSUE TITLE
Info Plus Button Functionality

### ISSUE THREAD

**Issue by AdnanAhsanNYCity** [gcivil-nyu-org/team-3-inperson#303] opened 2022-11-20 04:44 UTC
Maybe add the same plus button to the bookshelf of the user, after the initial "match" of books, I'm unable to get that info again.

**Comment by sjeremycohen** [comment] 2022-11-21 13:27
This is not a bug, this is a feature request - and one that's already in the product backlog. Closing

**Closed by sjeremycohen** 2022-11-21 13:27 UTC
Labels: bug, Testing Party
