### ISSUE TITLE
Testing Party: First Name and Last Name Change

### ISSUE THREAD

**Issue by as14680** [gcivil-nyu-org/team-3-inperson#299] opened 2022-11-19 22:25 UTC
While updating the user name and password the console shows the below errors. And after updating the user name and last name the account logs out every time. Not sure if this is intended or a bug, but it seems more like a bug.

Steps to replicate:
1. Login
2. Head over to the My Profile
3. Click on edit
4. Update the first name or last name and click update

Platform
MAC OS 13
Browser Safari

Screenshot for reference

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/25785714/202873633-35935bed-c22e-483f-8571-210313473eb2.png">

After Submission

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/25785714/202873661-1fd61bf3-990b-47a4-8bd2-685cbc710d54.png">

**Comment by Pankhurinyu** [comment] 2022-11-20 02:03
@as14680 
Hi ! 
   After updating the user name or any of your profile fields, you will be logged out and the system will take you to login page. This is intended
 Thanks 
Pankhuri

**Comment by sjeremycohen** [comment] 2022-11-21 13:22
Per @Pankhurinyu above, this is expected behavior. Closing.

**Closed by sjeremycohen** 2022-11-21 13:22 UTC
Labels: bug, Testing Party
